### ISSUE TITLE
Windows mouse cursors and clicks are not responding correctly

### ISSUE THREAD

**Issue by holmessh** [parhamoyan/qutewindow#3]
Hi,

When I run the demo codes (even the basic one with opening a main window only), I'm experiencing the following issues:
- No response to any mouse click
- Mouse cursor doesn't change when hovering the close, min, max window buttons
- Mouse cursor change to "left/right cursor" when mouse is hovering top, left, right edges and inside window
- Mouse cursor change to "bottom left/top right cursor" when mouse is hovering bottom left and right corners of window
- Cannot move window
- Aero snap not showing probably due to not reading the mouse correctly

It seems like the issue is not reading the mouse position and clicks correctly.  Please help.  I've been looking for something like this and finally found your work.

Please tell me how can I fix it.

Thanks!

**Comment by parhamoyan** [comment]
Hi, 
Which version of Windows are you using?

**Comment by parhamoyan** [comment]
Hi,
Which operating system ?

**Comment by holmessh** [comment]
Windows

**Comment by holmessh** [comment]
Windows 11

**Comment by parhamoyan** [comment]
> Windows 11

Alright lmc

**Comment by parhamoyan** [comment]
Weird, I can't reproduce it. It works fine on my laptop.

**Comment by holmessh** [comment]
Ok, I found out why.  As I was trying to video capture and share it with you, I realized these issues happen when VS code is on my secondary monitor.  This is my default setup.  I moved VS code to my primary monitor and run the code, everything works.  However, as soon as I drag the window to my second monitor, all issues come back.

**Comment by holmessh** [comment]
Hi, Just wondering is this still something you can look into?  Thanks

**Comment by parhamoyan** [comment]
Hi, I just reproduced it, I'm working on it rn.

**Comment by holmessh** [comment]
Cool, many thanks!

**Comment by parhamoyan** [comment]
I think it has been fixed

**Comment by holmessh** [comment]
It is still not working.  Here is what I've tried:
- uninstall old package
- install package again
- download the updated native_event.py and overwrite it in the site-packages folder
Is there anything I am doing wrong?

**Comment by holmessh** [comment]
Hi again,

Would you be able to look into it?  Is it all ok on your side?  I notice in native_event.py, line 30, isResizable() is not showing as a function when I type "." after widget.  Where as isMaximized is.  I am using VS Code.

Thanks

**Comment by parhamoyan** [comment]
Hi, 
I currently have exams until September 7th. I need to focus on studying right now, but once my exams are over, I will be available to work on this package.

**Comment by holmessh** [comment]
ok, cool!  Good luck on your exams.
